{
 "title": "DGMC System & API Performance Template",
 "tags": [
  "nodejs",
  "dgmc",
  "api"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dgmc_api_http_requests_total[1m])",
     "legendFormat": "Requests per second (Host: {{host}})"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(dgmc_api_http_request_duration_ms_sum[1m]) / rate(dgmc_api_http_requests_total[1m])",
     "legendFormat": "Global Avg Latency (Host: {{host}})"
    },
    {
     "expr": "rate(dgmc_api_db_latency_ms_sum[1m]) / rate(dgmc_api_http_requests_total[1m])",
     "legendFormat": "Avg Database Latency (Host: {{host}})"
    }
   ]
  },
  {
   "title": "System Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(dgmc_api_unmatched_departments_total[1m]) / rate(dgmc_api_http_requests_total[1m])) * 100",
     "legendFormat": "Error Rate % (Unmatched Joins)"
    }
   ]
  }
 ]
}