[server]
# Protocol (http, https, h2, socket)
protocol = http

# The ip address to bind to, empty will bind to all interfaces
http_addr = 

# The http port to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = localhost

# Redirect to correct domain if host header does not match domain
enforce_domain = false

root_url = %(protocol)s://%(domain)s:%(http_port)s/
serve_from_sub_path = false

[database]
# This configures Grafana's internal backend database (where it stores dashboards, users, etc.)
type = sqlite3
host = localhost:3306
name = grafana
user = root
password = rootpassword

[provisioning]
# This allows Grafana to automatically discover and connect to external data sources
enabled = true
datasources = /etc/grafana/provisioning/datasources
dashboards = /etc/grafana/provisioning/dashboards

[security]
# default admin user, created on startup
admin_user = admin
# default admin password, can be changed before first start of grafana
admin_password = admin
secret_key = SW2YcwTIb9zpOOhoPsMm

[auth.anonymous]
enabled = false

[users]
allow_sign_up = false

[dashboards]
versions_to_keep = 20

[log]
mode = console file
level = info
