apiVersion: 1

datasources:
  - name: DGMC_Meals_MySQL
    type: mysql
    url: 127.0.0.1:3311
    user: dgmc_user
    password: dgmc_password
    database: dgmc_meals
    isDefault: true
    jsonData:
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+

  - name: DGMC_Meals_SQLite_Legacy
    type: sqlite3
    url: file:/var/lib/grafana/dgmc_meals.db
    isDefault: false
